In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7])

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(7,)

In [7]:
a.dtype

dtype('int64')

In [8]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
a= np.array([[1,2,3,4],[5,6,7,8]])

In [10]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
a.shape

(2, 4)

In [12]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
np.ones((2,5),dtype='int64')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
arr =np.array([[1,2,3],[4,5,6]])

In [15]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [17]:
5 * arr

array([[ 5, 10, 15],
       [20, 25, 30]])

In [18]:
arr /arr

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [19]:
arr / arr

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [20]:
arr /2

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  2.5,  3. ]])

In [21]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [22]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [23]:
arr + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
3 -arr

array([[ 2,  1,  0],
       [-1, -2, -3]])

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr **3

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [29]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[5]

5

In [31]:
arr[2:9]

array([2, 3, 4, 5, 6, 7, 8])

In [33]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr[1][2]

6

In [37]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [0,1,2]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]]])

In [38]:
arr[0,1]

array([4, 5, 6])

In [39]:
arr[1,0,2]

9