In [1]:
import numpy as np

In [2]:
measure = np.array([
    [170,65,20],
    [180,80,25],
    [160,55,15]
])

In [3]:
measure

array([[170,  65,  20],
       [180,  80,  25],
       [160,  55,  15]])

In [5]:
A = np.array([
    [1,0,0],
    [0,1,0],
    [0,1,0],
    [0,0,1]
])

B = np.array([
    [158,50,84,63,86]
])

C = np.array([
    [1],
    [2],
    [0],
    [2],
    [0],
    
])

In [7]:
print (A,end='\n\n')
print (B,end='\n\n')
print(C)

[[1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]]

[[158  50  84  63  86]]

[[1]
 [2]
 [0]
 [2]
 [0]]


In [9]:
print("A.shape = "+ str(A.shape))
print("B.shape = "+str(B.shape))
print("C.shape = "+str(C.shape))

A.shape = (4, 3)
B.shape = (1, 5)
C.shape = (5, 1)


In [10]:
print(measure)

[[170  65  20]
 [180  80  25]
 [160  55  15]]


In [11]:
measure[1,2]

25

In [12]:
print(measure[0,:])
print(measure[0,:].shape)

[170  65  20]
(3,)


In [16]:
print(measure[0,:].reshape(1,-1))
print(measure[0,:].reshape(1,-1).shape)

[[170  65  20]]
(1, 3)


ここからよくわからん

In [18]:
print(measure[:,1])
print(measure[:,1].shape)

[65 80 55]
(3,)


In [20]:
print(measure[:,1].reshape(-1,1))
print(measure[:,1].reshape(-1,1).shape)

[[65]
 [80]
 [55]]
(3, 1)


In [21]:
#1.1.6 転置行列

In [22]:
print(measure)

[[170  65  20]
 [180  80  25]
 [160  55  15]]


In [23]:
print(measure.T)

[[170 180 160]
 [ 65  80  55]
 [ 20  25  15]]


In [24]:
D = np.array([
    [10,30],
    [20,40],
])

F = np.array([
    [1,2],
    [3,4],
])

In [25]:
print(D+F)

[[11 32]
 [23 44]]


In [26]:
print(D -F)

[[ 9 28]
 [17 36]]


In [27]:
a = np.array([1,2,3])
c = np.array([
    [1],
    [2],
    [3]
])

In [28]:
print(10*a)
print(10*c)

[10 20 30]
[[10]
 [20]
 [30]]


In [ ]:
J = np.array([
    [1,2,3,4]
    [5,6,7,8]
])